# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: William Fiset
title: 
email: william.alexandre.fiset@gmail.com
# website: www.github.com/williamfiset

# Social links
# twitter_username: facespics
github_username:  williamfiset
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: williamfiset
# pinterest_username: jekyll
youtube_username: channel/UCD8yeTczadqdARzQUp29PJw

# About Section
# about_title: About Me
about_profile_image: images/avatar.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's William and I'm a senior network system administrator. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs

  Support me by encouraging me to create more content:  

  <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
  <input type="hidden" name="cmd" value="_donations" />
  <input type="hidden" name="business" value="4BXCN4CXE8KAY" />
  <input type="hidden" name="currency_code" value="USD" />
  <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif" border="0" name="submit" title="PayPal - The safer, easier way to pay online!" alt="Donate with PayPal button" />
  <img alt="" border="0" src="https://www.paypal.com/en_US/i/scr/pixel.gif" width="1" height="1" />
  </form>


# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
